repos:
  - repo: /Users/jian/Documents/github/cercis
    rev: 0.1.5
    hooks:
      - id: cercis

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: .*\.ya?ml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
