repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/jsh9/cercis
    rev: 0.2.0
    hooks:
      - id: cercis

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.3.3
    hooks:
      - id: validate_manifest

  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.0.4
    hooks:
      - id: markdown-toc-creator

  - repo: local
    hooks:
      - id: copy_readme
        name: copy_readme
        entry: python .pre_commit_helper_scripts/copy_readme.py
        language: system
        types: [python]
